### ISSUE TITLE
Decrypting

### ISSUE THREAD

**Issue by spacechicken** [mikealeonetti/drip-auto-hydrater#1]
Hey Mikeal,
Followed your process but keep getting the PK needs to be 32 Bytes? Tried it with a uncrypted PK and it works fine.

Any ideas, or process that I should follow to check if I have missed anything?

**Comment by mikealeonetti** [comment]
Hi! Did you create a 32 byte base64 encoded key?

Usually `openssl rand -base64 32` will do this for you.

**Comment by mikealeonetti** [comment]
Closing because I haven't heard back.
