### ISSUE TITLE
Reservior Auto Hydrator

### ISSUE THREAD

**Issue by spacechicken** [mikealeonetti/drip-auto-hydrater#2]
Hi Mike,

Have you or can you create an Auto Hydrator for the Reservior?

**Comment by mikealeonetti** [comment]
Maybe. Do you still want this?

**Comment by xecman** [comment]
Hi @mikealeonetti ,

This seems to be the only Drip Auto-Hydrater publicly available.  Am I able to contact you for some help in getting started - if so, how?  I'm hitting a snag out of the gate.  Also, would this work on my Mac or is there a Mac version?

Thanks!

Mike

**Comment by mikealeonetti** [comment]
Hi @xecman . Feel free to contact me on Telegram as @@HeyItsMikeyA. No promises about how quickly I can get back to you, though.

This works on Mac as long as you have node.js installed.

**Comment by xecman** [comment]
Thanks Mike I’ll reach out. Much appreciated!

Mike
