### ISSUE TITLE
ARK token

### ISSUE THREAD

**Issue by spacechicken** [mikealeonetti/drip-auto-hydrater#4]
Hi Mike,

Are you able to list where and what format I need to add my ARK details for the script please. I notice on the account set up it does DRIP and not ARK as an option - just need to know where and how I put my wallet address and secret key etc.

Thanks very much.

**Comment by mikealeonetti** [comment]
I see you messaged me on TG. But you can also look in the README.md. There is a description there. I'll see you on TG either way.
