### ISSUE TITLE
Use Pocket (POKT) Network

### ISSUE THREAD

**Issue by geoff-ellison** [mikealeonetti/drip-auto-hydrater#5]
Thank you for this excellent project. I'm wanting to extend this to make use of Pocket network in order to reduce gas fees on BSC. I can see where to add the network URL (in `config/default/main.json`) but cannot figure out how to change GWEI from the default of `3` down to `1`. I would be grateful for any suggestions.
Thanks.

**Comment by mikealeonetti** [comment]
Hello! To change networks you can add into your config/local.json the following:
```
	"bsc" : {
		"ws" : "network_of_your_choice"
	}
```
It's how I test it. This way you don't have to modify the default config variables.

As far as setting the gas price, you'll have to modify the code. If you could find a good way to streamline it I would definitely accept a pull request to merge it in.

Look in inc/account.js for the tryExecuteTxn function. This is where the gas is set. You'll also notice it adds a little bit more gas to the transaction doesn't fail.

But you'll have to modify the following object to help you:
```
		// The opts
		const opts = {
			...extras,
			'to' : module.options.address,
			gas,
			data
		};
```
Here is the signTransaction function which it is called on: https://docs.web3js.org/api/web3-eth-accounts/function/signTransaction.  Note it overrides the Transaction object: https://docs.web3js.org/api/web3-eth-accounts/class/Transaction.

I haven't experimented with it and gas amounts.

It may be as simple as commenting out "gas" and adding 

```
gasPrice : web3.utils.toWei("1", "gwei"),
```

So it'll look like this:

```
		// The opts
		const opts = {
			...extras,
			'to' : module.options.address,
			gasPrice : web3.utils.toWei("1", "gwei"),
			data
		};
```

Have not tested though.

**Comment by spacechicken** [comment]
Hey just wondering @geoff-ellison if you got it to work with POKT. Hey Mike I think this is a good update to have to save gas fees.

**Comment by spacechicken** [comment]
Hey guys,
So I have added the BSC RPC POKT to my metamask:
endpoint URL:https://bsc-rpc.gateway.pokt.network/

So, does that mean that current:
	},
	"bsc" : {
		"ws" : "https://bsc-dataseed1.binance.org:443"
	},
	
	gets replaced with:
	
	},
	"bsc" : {
		"ws" : "[https://bsc-rpc.gateway.pokt.network"
	},

Please confirm and I could not find this code in the config are you just saying to add this to the config file:
// The opts
		const opts = {
			...extras,
			'to' : module.options.address,
			gasPrice : web3.utils.toWei("1", "gwei"),
			data
		};

Thanks for your help!

**Comment by geoff-ellison** [comment]
Hey @mikealeonetti thank you, you set me on the right track. With a bit of surgery I got it working.


@spacechicken asked:

> Hey just wondering @geoff-ellison if you got it to work with POKT. 

Yes. Here is what I did:

in `config/local.json` add an element within the main array:
```
,
  "bsc": {
    "ws": "https://bsc-rpc.gateway.pokt.network:443"
  }
```
and

in `inc/account.js` update the declaration of `opts` (around line 163) to the following:
```
		const opts = {
			...extras,
			'to' : module.options.address,
			gasPrice : Web3.utils.toWei("1", 'gwei'),
			gas,
			data
		};
```

and

in `drivers/faucet.js` (around line 80) I changed the minimum required BNB balance for gas from 0.02 to 0.005:
```
		if( gasBalance.gt( 0.005 ) ) {
			log.message.info( "We have enough gas so we don't have to sell %s", this.key );

			return( false ); // We have enough. Don't process.
		}
```

> Hey Mike I think this is a good update to have to save gas fees.

I agree @spacechicken but I don't think I'll get a chance to do a pull request myself, so please feel free. If you do it, I would strongly recommend that the last change (the minimum BNB balance) should come from a config variable, or if not set, a default of `0.02`, which was the original value. Likewise the GWEI value in `gasPrice` in the `opts` constant should be able to be set from a config var as well, or if not set, it should default to `3`. That way support for POKT could be added to the project, but wouldn't break operations for anyone who isn't using it. And those who wish to use it can do so simply by adding 3 values to their `local.json`.

G

**Comment by spacechicken** [comment]
Hey @geoff-ellison thanks so much @mikealeonetti your DRIP stuff is epic. Hey @geoff-ellison do you want to contact me I'd be interested in other automation if you are doing it like auto moving BNB to wallets at a certain BNB level and auto sweeping of DRIP and swapping at max level - Any ideas to add this stuff @mikealeonetti for the future. As my drip wallet numbers are getting bigger and I am so happy that I have reduced my daily fees as it adds up!!

Great work and thanks to both of once again!!

**Comment by mikealeonetti** [comment]
Thank you @spacechicken and @geoff-ellison.

With the changes I have added the following:

You can now use the option "gasInGwei" to set custom a custom gasPrice. For example:

```json
{
        "bsc" : {
                "ws" : "https://bsc-rpc.gateway.pokt.network:443",
                "gasInGwei" : 1
        }
}
```

Also, you can now set the minimum BNB balance before a sell is triggered using "forceSellMinGas". You can use like this:

```json
{
        "accounts" : [
        {
                "key" : "main",
                "driver" : "faucet",
                "id" : "0x...",
                "actions" : [ "hydrate" ],
                "enabled" : true,
                "forceSellMinGas" : 0.005
        }
        ]
}
```

Thanks for the compliments and the ideas. Let me know if this causes any issues.

**Comment by spacechicken** [comment]
Hey, is this the right code, I'm not sure if I need the other bracket at the bottom:
 "accounts": [
    {
      "keyFile": "0000....",
      "key": "Drip1",
      "driver": "faucet",
      "actions": [
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate"],
        "enabled" : true,
        "forceSellMinGas" : 0.005
      ],
      "id": "555xxxxx"
    },

**Comment by mikealeonetti** [comment]
I think this is what you're looking for:
```json
  "accounts": [
    {
      "keyFile": "0000....",
      "key": "Drip1",
      "driver": "faucet",
      "actions": [
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate",
        "hydrate"
      ],
      "enabled": true,
      "forceSellMinGas": 0.005,
      "id": "555xxxxx"
    }
  ]
```

You also don't have to repeat "hydrate" 7 times. You can just write it once and it'll repeat forever. Like my schedule is

```json
[ "hydrate", "sell" ]
```
Which is an alternating schedule. It'll hydrate the first day and sell all drip the second. Then it will repeat that forever.
